//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuoKuWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCdetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCdetails()
        {
            this.Download = new HashSet<Download>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<int> CollectionNumber { get; set; }
        public Nullable<int> DownloadNumber { get; set; }
        public Nullable<int> SeeNumber { get; set; }
        public string PictureURL { get; set; }
        public string FileURL { get; set; }
        public int UserID { get; set; }
        public string UploadTime { get; set; }
        public bool SCState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Download> Download { get; set; }
    }
}
